leftnav:
- identifier: 137033bb-371f-28e3-ee22-66f6d6d22673
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 903c642d-3960-64c7-f441-b06acfd5684e
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 58d49c52-f22f-c6cf-f648-a985b43b54e9
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: c3c6f131-89d0-405b-3d9a-d1bd82340b19
  name: Exams
  pageRef: /pages/exams
  weight: 40
